## NumPy
NumPyは「Numercal Python」の略で「数的Python」といった意味です。Python の数値計算における<br>
最も重要なパッケージです。科学技術計算、機械学習などの多くのPythonパッケージは共通語として<br>
NumPyの配列オブジェクトを用いています。


### NumPy ndarray : 多次元配列オブジェクト
ndarray は NumPyの基本要素の１つで、(N-Dimentional array) N次元配列オブジェクトを意味します。<br>
ndarray は Python環境における高速かつ大規模なデータ処理を提供します。まず算術操作から見て<br>
いきます。ndarray の算術操作は、その配列要素すべてに作用します。一括計算はつぎの例のように<br>
行うことができます。


乱数列を生成します。

In [1]:
import numpy as np

data = np.random.randn(2,3)
data

array([[ 0.59347365, -0.39186205,  0.01704146],
       [-0.77147868,  0.52233118, -0.12923899]])

すべての要素が10倍されます

In [2]:
data * 10

array([[ 5.93473645, -3.91862047,  0.17041461],
       [-7.71478683,  5.22331179, -1.29238987]])

すべての対応する位置どうしの要素が加算されます。

In [3]:
data + data

array([[ 1.18694729, -0.78372409,  0.03408292],
       [-1.54295737,  1.04466236, -0.25847797]])

ndarray はつぎのような特徴を持ちます。
- ndarrayの多次元配列の要素はすべて同じ型である必要があります。
- shapeという属性があり、配列の次元ごとの要素数をタプルで格納しています。
- dtypeという属性があり、配列要素に期待される型を示しています。

In [4]:
data.shape

(2, 3)

In [5]:
data.dtype

dtype('float64')

### ndarrayの生成
ndarrayオブジェクトの生成するには、NumPyのarray関数を用います。array関数は、引数にシーケンス型<br>
やそれに類する変数を取り、そのデータを格納したndarray変数を返します。リストをndarryにするには、<br>
つぎのようにします。

In [6]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

リストの中にリストを持つような、ネストしているシーケンスオブジェクトでは、ネスト構造の内側の<br>
シーケンス同士が一致する場合にndarrayオブジェクトが生成されます。

In [7]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

ndim属性は配列の次元数を格納しています。

In [8]:
arr2.ndim

2

In [9]:
arr2.shape

(2, 4)

dtypeを明示的に指定せずにnp.arrayを呼び出すと、np.arrayは最適は型を推測しようとします。

In [10]:
arr2.dtype

dtype('int32')

#### ndarray生成関数
|関数|説明|
|:---|:---|
|array|入力にリスト、タプル、Python配列、その他列挙型といったデータを引数として受け取りndarrayを生成する。|
|asarray|arrayと同様にndarrayを生成する。ただし入力がndarrayの場合は新規に変数を生成しない。|
|arange|Pythonの組み込みrange関数と同じ動作で,ndarrayを生成する。|
|ones|onesは指定されたサイズのndarrayを指定されたdtyeで生成し、要素をすべて1で埋める。|
|zeros|onesと同様にndarrayを生成し、要素をすべて0で埋める。|
|empty|onesと同様にndarrayを生成するが、各要素は初期化されず不定のまま。|
|||

## ndarrayのデータ型
dtypeはndarrayのデータ型です。これはメモリ上のデータ形式を示す特殊なオブジェクトです。dtypeの<br>
役割は、あるndarray が格納されるメモリ範囲が特定のデータ型で解釈されることを示すものです。

In [11]:
arr1 = np.array([1, 2, 3],dtype=np.float64)
print(arr1, arr1.dtype)

[1. 2. 3.] float64


In [12]:
arr1 = np.array([1, 2, 3],dtype=np.int32)
print(arr1, arr1.dtype)

[1 2 3] int32


#### NumPyの主なデータ型
|型|型コード|説明|
|:---|:---|:---|
|int8, unit8|i1,u1|符号あり/なしの8ビット整数型(1 byte)|
|int16, unit16|i2,u2|符号あり/なしの16ビット整数型|
|int32, unit32|i4,u4|符号あり/なしの32ビット整数型|
|int64, unit64|i8,u8|符号あり/なしの64ビット整数型|
|float32|f4もしくはf|単精度浮動小数点数。Cのfloatと同じ|
|float64|f8もしくはd|倍精度浮動小数点数。Cのdoubleと同じ|
|bool|?|真偽値型。True(真), False(偽)を格納する|
|object|O|Pythonオブジェクト型|
|string_|S|固定長の文字列型。1文字あたり1バイト。例えば10文字はdtype='S10'|
|unicode_|U|固定長ユニコードの文字列型。1文字当たりのバイト数宇は環境依存|
||||


In [13]:
arr1 = np.array([1, 2, 3],dtype='i2')
print(arr1, arr1.dtype)

[1 2 3] int16


In [14]:
arr1 = np.array([1, 0, 1],dtype='?')
print(arr1, arr1.dtype)

[ True False  True] bool


In [15]:
numeric_string = np.array(['1.25','2.54'], dtype=np.string_)
numeric_string

array([b'1.25', b'2.54'], dtype='|S4')

In [16]:
ustring = np.array(['月曜','火曜'])
ustring

array(['月曜', '火曜'], dtype='<U2')

## ndarrayの算術演算
ndarryaでは、要素ごとの処理のためにわざわざ繰り返し文を書く必要はありません。この機能はベクトル演算と<br>
呼ばれるNumPyの重要な特徴のひとつです。同じサイズのndarray同士の算術演算は、同位置の要素同士で計算<br>
されます。

In [17]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [19]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

スカラーとndarrayとの算術演算の場合、要素ごとにその加減乗除が計算されます。

In [20]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [21]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

ndarray間を比較したとき、その結果は同じ要素数の真偽配列として戻されます。

In [22]:
arr2 = np.array([[0, 4, 1],[7, 2, 12]])
arr2

array([[ 0,  4,  1],
       [ 7,  2, 12]])

In [23]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [24]:
%%html
<style>
table {float:left}
</style>